repository: EzraKlukas/ezraklukas.github.io
url: "https://ezraklukas.github.io"
baseurl: ""

title: Ezra Klukas Portfolio

name: Ezra Klukas
headline: 3rd year engineering physics student
description: >-
  I love to serve others in teams, and get excited to ask why things are the way
  they are. I approach academics very rigorously and always seek out the deeply
  connected mathematics and physics underlying everything we do, use, and create.
  I've emphasized building useful practical engineering skills ontop of my
  academic foundation to make me a solid engineer and enable me to do really cool
  things with what I've learned!

profile_image: ./assets/images/profile-image/ezraklukas_profile_img.jpg
resume-url: /assets/resume/resume.pdf

external-links:
  linkedin: ezra-klukas-23abb826b/
  github: EzraKlukas
  discord: ezraklukas
  gmail: ezraklukas@gmail.com

skills:
  - category: 3D Modeling
    tools:
      - Onshape
  - category: Prototyping
    tools:
      - FDM
      - Laser Cutting
      - Water Jet Cutting
      - ESP32 / Arduino / STM32
      - Breadboarding for circuit testing
      - Oscilloscope, logic analyzer, DMM for circuit debugging
  - category: PCB Design
    tools:
      - KiCad

formspree-key: https://formspree.io/f/xeejvbrp

colors:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

collections:
  projects:
    output: true
    permalink: /projects/:path/

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects

exclude:
  - unofficial_transcript.pdf
  - vendor
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
  - node_modules
  - Gemfile
  - Gemfile.lock
  - .bundle
  - .sass-cache
  - .jekyll-cache
